"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { requireUser } from "@/lib/auth/session"; import { verifyCsrf } from "@/lib/auth/csrf"; import { db } from "@/lib/database"; import { websiteSchema } from "@/lib/validation/website"; import { validatePublicUrl, assertPublicHost } from "@/lib/security/network"; import { config } from "@/lib/config"; import { monitorWebsite } from "@/modules/monitoring/monitor-website";
function object(form:FormData){return Object.fromEntries(form.entries())}
async function validated(form:FormData){const data=websiteSchema.parse(object(form));const url=await validatePublicUrl(data.publicUrl);if(!config().ALLOWED_TLS_PORTS.split(",").map(Number).includes(data.port))throw new Error("TLS port is not approved");if(data.hostname!==url.hostname)throw new Error("Hostname must match the public URL");if(data.checkOriginCertificate){if(!data.originConnectHost||!data.originSniHostname)throw new Error("Origin host and SNI are required");await assertPublicHost(data.originConnectHost,config().ALLOW_PRIVATE_ORIGIN_HOSTS);}return {...data,publicUrl:url.toString(),originConnectHost:data.originConnectHost||null,originSniHostname:data.originSniHostname||null};}
export async function createWebsite(form:FormData){await requireUser();await verifyCsrf(form.get("csrf"));const website=await db.website.create({data:await validated(form)});redirect(`/websites/${website.id}`)}
export async function updateWebsite(id:string,form:FormData){await requireUser();await verifyCsrf(form.get("csrf"));await db.website.update({where:{id},data:await validated(form)});redirect(`/websites/${id}`)}
export async function deleteWebsite(id:string,csrf:string){await requireUser();await verifyCsrf(csrf);await db.website.delete({where:{id}});revalidatePath("/dashboard")}
export async function toggleWebsite(id:string,csrf:string){await requireUser();await verifyCsrf(csrf);const w=await db.website.findUniqueOrThrow({where:{id},select:{enabled:true}});await db.website.update({where:{id},data:{enabled:!w.enabled}});revalidatePath("/dashboard")}
export async function checkNow(id:string,csrf:string){await requireUser();await verifyCsrf(csrf);const w=await db.website.findUniqueOrThrow({where:{id}});await monitorWebsite(w);revalidatePath("/dashboard");revalidatePath(`/websites/${id}`)}
