CREATE TYPE "Role" AS ENUM ('ADMIN');
CREATE TYPE "CheckType" AS ENUM ('PUBLIC','ORIGIN');
CREATE TYPE "CheckStatus" AS ENUM ('HEALTHY','WARNING','URGENT','CRITICAL','EXPIRED','INVALID','UNAVAILABLE','UNKNOWN');
CREATE TYPE "HttpStatus" AS ENUM ('AVAILABLE','UNAVAILABLE','CLOUDFLARE_ERROR','UNKNOWN');
CREATE TYPE "AlertDeliveryStatus" AS ENUM ('PENDING','SENT','FAILED','SKIPPED');
CREATE TYPE "MonitoringRunStatus" AS ENUM ('RUNNING','COMPLETED','PARTIAL','FAILED','SKIPPED');
CREATE TYPE "TriggerType" AS ENUM ('SCHEDULED','MANUAL');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"email" TEXT NOT NULL UNIQUE,"passwordHash" TEXT NOT NULL,"name" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'ADMIN',"enabled" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"lastLoginAt" TIMESTAMP(3));
CREATE TABLE "Website" ("id" TEXT PRIMARY KEY,"clientName" TEXT NOT NULL,"websiteName" TEXT NOT NULL,"publicUrl" TEXT NOT NULL,"hostname" TEXT NOT NULL,"port" INTEGER NOT NULL DEFAULT 443,"enabled" BOOLEAN NOT NULL DEFAULT true,"checkPublicCertificate" BOOLEAN NOT NULL DEFAULT true,"checkHttp" BOOLEAN NOT NULL DEFAULT true,"usesCloudflare" BOOLEAN NOT NULL DEFAULT false,"checkOriginCertificate" BOOLEAN NOT NULL DEFAULT false,"originConnectHost" TEXT,"originSniHostname" TEXT,"tlsTimeoutMs" INTEGER NOT NULL DEFAULT 10000,"httpTimeoutMs" INTEGER NOT NULL DEFAULT 15000,"hostingProvider" TEXT,"renewalMethod" TEXT,"responsibleParty" TEXT,"notes" TEXT,"alertRecipients" TEXT[],"alertThresholds" INTEGER[],"lastCheckedAt" TIMESTAMP(3),"lastStatus" "CheckStatus" NOT NULL DEFAULT 'UNKNOWN',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CertificateCheck" ("id" TEXT PRIMARY KEY,"websiteId" TEXT NOT NULL REFERENCES "Website"("id") ON DELETE CASCADE,"checkType" "CheckType" NOT NULL,"checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"success" BOOLEAN NOT NULL,"certificatePresent" BOOLEAN NOT NULL,"authorized" BOOLEAN NOT NULL,"authorizationError" TEXT,"validFrom" TIMESTAMP(3),"expiresAt" TIMESTAMP(3),"daysRemaining" INTEGER,"issuer" JSONB,"subject" JSONB,"subjectAlternativeNames" TEXT[],"fingerprint" TEXT,"serialNumber" TEXT,"protocol" TEXT,"cipher" TEXT,"connectHost" TEXT NOT NULL,"sniHostname" TEXT NOT NULL,"durationMs" INTEGER NOT NULL,"status" "CheckStatus" NOT NULL,"errorCode" TEXT,"errorMessage" TEXT);
CREATE TABLE "HttpCheck" ("id" TEXT PRIMARY KEY,"websiteId" TEXT NOT NULL REFERENCES "Website"("id") ON DELETE CASCADE,"checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"success" BOOLEAN NOT NULL,"statusCode" INTEGER,"finalUrl" TEXT,"responseTimeMs" INTEGER NOT NULL,"redirectCount" INTEGER NOT NULL,"status" "HttpStatus" NOT NULL,"errorCode" TEXT,"errorMessage" TEXT);
CREATE TABLE "AlertEvent" ("id" TEXT PRIMARY KEY,"websiteId" TEXT NOT NULL REFERENCES "Website"("id") ON DELETE CASCADE,"certificateCheckId" TEXT REFERENCES "CertificateCheck"("id") ON DELETE SET NULL,"alertType" TEXT NOT NULL,"threshold" INTEGER,"recipient" TEXT NOT NULL,"subject" TEXT NOT NULL,"deliveryStatus" "AlertDeliveryStatus" NOT NULL DEFAULT 'PENDING',"providerMessageId" TEXT,"errorMessage" TEXT,"dedupKey" TEXT NOT NULL UNIQUE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"sentAt" TIMESTAMP(3));
CREATE TABLE "MonitoringRun" ("id" TEXT PRIMARY KEY,"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),"status" "MonitoringRunStatus" NOT NULL DEFAULT 'RUNNING',"websitesProcessed" INTEGER NOT NULL DEFAULT 0,"checksSuccessful" INTEGER NOT NULL DEFAULT 0,"checksFailed" INTEGER NOT NULL DEFAULT 0,"alertsSent" INTEGER NOT NULL DEFAULT 0,"errorMessage" TEXT,"triggerType" "TriggerType" NOT NULL);
CREATE INDEX "Website_enabled_idx" ON "Website"("enabled");
CREATE INDEX "Website_clientName_idx" ON "Website"("clientName");
CREATE INDEX "Website_lastStatus_idx" ON "Website"("lastStatus");
CREATE INDEX "CertificateCheck_websiteId_checkedAt_idx" ON "CertificateCheck"("websiteId","checkedAt" DESC);
CREATE INDEX "CertificateCheck_status_checkedAt_idx" ON "CertificateCheck"("status","checkedAt");
CREATE INDEX "CertificateCheck_fingerprint_idx" ON "CertificateCheck"("fingerprint");
CREATE INDEX "HttpCheck_websiteId_checkedAt_idx" ON "HttpCheck"("websiteId","checkedAt" DESC);
CREATE INDEX "HttpCheck_status_checkedAt_idx" ON "HttpCheck"("status","checkedAt");
CREATE INDEX "AlertEvent_websiteId_createdAt_idx" ON "AlertEvent"("websiteId","createdAt" DESC);
CREATE INDEX "MonitoringRun_startedAt_idx" ON "MonitoringRun"("startedAt" DESC);
CREATE INDEX "MonitoringRun_status_idx" ON "MonitoringRun"("status");
